# Generated by Django 4.2.1 on 2023-05-09 14:15

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border', models.ImageField(db_column='border', upload_to='images/')),
                ('price', models.IntegerField(db_column='price')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_front', models.ImageField(upload_to='images/')),
                ('image_back', models.ImageField(upload_to='images/')),
                ('borders', models.ManyToManyField(db_column='borders', to='news.bordermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=256)),
                ('image', models.ImageField(db_column='image', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(db_column='full_name')),
                ('email', models.TextField(db_column='email')),
                ('whatsapp', models.TextField(db_column='whatsapp')),
                ('message', models.TextField(db_column='message')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='full_name', max_length=128)),
                ('country', models.CharField(db_column='country', max_length=64)),
                ('city', models.CharField(db_column='city', max_length=64)),
                ('address', models.TextField(db_column='address')),
                ('post_code', models.CharField(db_column='post_code', max_length=256)),
                ('email', models.CharField(db_column='email', max_length=64)),
                ('payment_status', models.BooleanField(db_column='payment_status', default=False)),
                ('cart_front', models.ImageField(db_column='cart_front', upload_to='images/')),
                ('cart_back', models.ImageField(db_column='cart_back', upload_to='images/')),
                ('cart_id', models.IntegerField(db_column='cart_id')),
                ('color_id', models.IntegerField(db_column='color_id')),
                ('border_id', models.IntegerField(db_column='border_id')),
            ],
        ),
        migrations.CreateModel(
            name='UpdatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(db_column='email')),
                ('first_name', models.TextField(db_column='first_name')),
                ('last_name', models.TextField(db_column='last_name')),
                ('instagram', models.TextField(db_column='instagram')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('description', models.TextField(db_column='description')),
                ('full_name', models.TextField(db_column='full_name')),
            ],
            options={
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created_at', 'updated_at'], name='news_review_created_1e06ce_brin')],
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(db_column='banner', upload_to='images/')),
                ('image_front', models.ImageField(db_column='image_front', upload_to='images/')),
                ('image_back', models.ImageField(db_column='image_back', upload_to='images/')),
                ('price', models.IntegerField(db_column='price')),
                ('cart', models.ForeignKey(blank=True, db_column='cart', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.cartmodel')),
            ],
        ),
    ]
