# Generated by Django 4.2.1 on 2023-05-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bordermodel',
            options={'verbose_name': 'Border', 'verbose_name_plural': 'Border'},
        ),
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Color'},
        ),
        migrations.AlterModelOptions(
            name='contactsmodel',
            options={'verbose_name': 'Contacts', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Review'},
        ),
        migrations.AlterModelOptions(
            name='updatesmodel',
            options={'verbose_name': 'Updates', 'verbose_name_plural': 'Updates'},
        ),
        migrations.RemoveIndex(
            model_name='reviewmodel',
            name='news_review_created_1e06ce_brin',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='borders',
            field=models.ManyToManyField(db_column='borders', related_name='carts', to='news.bordermodel'),
        ),
        migrations.AlterModelTable(
            name='bordermodel',
            table='border',
        ),
        migrations.AlterModelTable(
            name='cartmodel',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table='category',
        ),
        migrations.AlterModelTable(
            name='colormodel',
            table='color',
        ),
        migrations.AlterModelTable(
            name='contactsmodel',
            table='contacts',
        ),
        migrations.AlterModelTable(
            name='ordermodel',
            table='order',
        ),
        migrations.AlterModelTable(
            name='reviewmodel',
            table='review',
        ),
        migrations.AlterModelTable(
            name='updatesmodel',
            table='updates',
        ),
    ]
